"""empty message

Revision ID: 24607cf665ee
Revises: 7344b6f65ca4
Create Date: 2025-04-13 18:57:04.581957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24607cf665ee'
down_revision: Union[str, None] = '7344b6f65ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'check_in',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('attendance', 'check_out',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('attendance', 'override_time',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.drop_column('student', 'position')
    op.drop_column('student', 'department')
    op.add_column('tag_log', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('tag_log', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag_log', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'tag_log', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_log', type_='foreignkey')
    op.drop_constraint(None, 'tag_log', type_='foreignkey')
    op.drop_column('tag_log', 'course_id')
    op.drop_column('tag_log', 'student_id')
    op.add_column('student', sa.Column('department', sa.VARCHAR(length=100), nullable=True))
    op.add_column('student', sa.Column('position', sa.VARCHAR(length=100), nullable=True))
    op.alter_column('attendance', 'override_time',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('attendance', 'check_out',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('attendance', 'check_in',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
